import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "MMLab - Multimedia Laboratory",
    description: "Generated by create next app",
    keywords: ["key1","key2"],
};



import {
    Card,
    CardContent,
    CardDescription,
    CardFooter,
    CardHeader,
    CardTitle,
} from "@/components/ui/card"



import { FadeIn } from "@/components/animation/fade-in"
import { RollinggText1 } from "@/components/animation/rolling-text-1"
import { RollinggText2 } from "@/components/animation/rolling-text-2"
import { RollinggText3 } from "@/components/animation/rolling-text-3"



import { news } from "@/data/news"



export default function Home() {
    return (
        <main>



            {/* Landing */}
            <div className="w-full h-svh flex flex-row justify-center items-center pl-6 pr-6 bg-gradient-to-br from-indigo-300 via-yellow-400 to-pink-500 bg-fixed">
                <div className="w-full max-w-7xl flex flex-col gap-6 select-none">
                    {/* <FadeIn>
                        <Image src="/logos/jc_stem_lab.png" width={200} height={200} alt="e"/>
                    </FadeIn> */}
                    <h1 className="font-bold text-6xl sm:text-7xl md:text-8xl lg:text-9xl text-white">
                        <FadeIn>Multimedia</FadeIn>
                    </h1>
                    <h1 className="font-bold text-6xl sm:text-7xl md:text-8xl lg:text-9xl text-white">
                        <FadeIn>Laboratory</FadeIn>
                    </h1>
                </div>
            </div>



            <FadeIn>
                <h2 className='p-6 pt-10 pb-10 md:p-20 min-h-64 lg:min-h-96 h-full flex flex-col justify-center font-bold text-3xl sm:text-4xl md:text-5xl lg:text-6xl gap-3 bg-gradient-to-br from-indigo-300 via-yellow-400 to-pink-500'>
                    <RollinggText1/>
                    <RollinggText2/>
                    <RollinggText3/>
                </h2>
            </FadeIn>



            <div className="w-full pl-6 pr-6 flex flex-col items-center mt-20">
                <h2 className="w-full max-w-7xl text-3xl sm:text-4xl md:text-5xl lg:text-6xl font-bold flex flex-col gap-3"> 
                    <FadeIn>
                        Explore
                    </FadeIn>
                    <FadeIn>
                        News and Highlights
                    </FadeIn>
                </h2>
            </div>
            <div className="w-full pl-6 pr-6 flex flex-col items-center mb-20">
                <div className="w-full max-w-7xl mt-10 flex flex-col lg:flex-row justify-between gap-6">
                    <div className="w-full flex flex-col gap-6">
                        {news.slice(0,2).map((item) => (
                            <FadeIn key={item.title}>
                                <div>
                                    <Card className="border-border bg-pink-800">
                                        <CardHeader>
                                            <CardTitle className="text-xl text-white">{item.title}</CardTitle>
                                            <CardDescription className="text-white">{item.date}</CardDescription>
                                        </CardHeader>
                                        <CardContent>
                                            <p className="text-white">{item.detail}</p>
                                        </CardContent>
                                        <CardFooter className="text-white flex justify-end">
                                            <a href={item.link} target="_blank" className="hover:underline">More</a>
                                        </CardFooter>
                                    </Card>
                                </div>
                            </FadeIn>
                        ))}   
                    </div>
                    <div className="w-full flex flex-col gap-6">
                        {news.slice(2,news.length).map((item) => (
                            <FadeIn key={item.title}>
                                <div>
                                    <Card className="border-pink-800 bg-pink-800" key={item.title}>
                                        <CardHeader>
                                            <CardTitle className="text-xl text-white">{item.title}</CardTitle>
                                            <CardDescription className="text-white italic">{item.date}</CardDescription>
                                        </CardHeader>
                                        <CardContent>
                                            <p className="text-white">{item.detail}</p>
                                        </CardContent>
                                        <CardFooter className="text-white flex justify-end">
                                            <a href={item.link} target="_blank" className="hover:underline">More</a>
                                        </CardFooter>
                                    </Card>
                                </div>
                            </FadeIn>
                        ))}   
                    </div>
                </div>
            </div>



            
                <div className="w-full flex flex-col lg:flex-row">
                    <div className="flex-1/3 ]"></div>
                    <div className="flex-2/3">
                        <FadeIn>
                            <div className="flex flex-col p-6 pt-10 pb-10 lg:p-20 gap-6">
                            
                                <h1 className="text-xl font-bold">
                                    AgiBot World Colosseo: A Large-scale Manipulation Platform for Scalable and Intelligent Embodied Systems
                                </h1>
                                <p>
                                    We explore how scalable robot data can address real-world challenges for generalized robotic manipulation. Introducing AgiBot World, a large-scale platform comprising over 1 million trajectories across 217 tasks in five deployment scenarios, we achieve an order-of-magnitude increase in data scale compared to existing datasets. 
                                </p><p>
                                    Accelerated by a standardized collection pipeline with human-in-the-loop verification, AgiBot World guarantees high-quality and diverse data distribution. It is extensible from grippers to dexterous hands and visuo-tactile sensors for fine-grained skill acquisition. Building on top of data, we introduce Genie Operator-1 (GO-1), a novel generalist policy that leverages latent action representations to maximize data utilization, demonstrating predictable performance scaling with increased data volume. Policies pre-trained on our dataset achieve an average performance improvement of 30% over those trained on Open X-Embodiment, both in in-domain and out-of-distribution scenarios. 
                                </p><p>
                                    GO-1 exhibits exceptional capability in real-world dexterous and long-horizon tasks, achieving over 60% success rate on complex tasks and outperforming prior RDT approach by 32%. 
                                </p><p>
                                    By open-sourcing the dataset, tools, and models, we aim to democratize access to large-scale, high-quality robot data, advancing the pursuit of scalable and general-purpose intelligence.
                                </p>
                            </div>
                        </FadeIn>
                    </div>
                </div>
            
                

        </main>
    );
}
