import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "JC STEM LAB",
    description: "Generated by create next app",
    keywords: ["key1","key2"],
};



import Image from 'next/image'



export default function Home() {
    return (
        <main className='h-svh w-full flex flex-col justify-center items-center'>
            <div className="flex flex-col gap-6">
                <Image src="/logos/jc_stem_lab.png" width={50} height={50} alt="e"/>
                <h1 className="font-bold text-6xl">
                    JC STEM
                </h1>
                <h1 className="font-bold text-6xl">
                    LAB
                </h1>
            </div>
                
        </main>
    );
}
