import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "Publication",
    description: "Generated by create next app",
    keywords: ["key1","key2"],
};



import Image from 'next/image'
import { AspectRatio } from "@/components/ui/aspect-ratio"
import { Separator } from "@/components/ui/separator"



import { FadeIn } from "@/components/animation/fade-in"



export default function Home() {
    return (
        <main>



            {/* Landing */}
            <div className="w-full h-svh flex flex-row justify-center items-center pl-6 pr-6 bg-gradient-to-br from-indigo-300 via-yellow-400 to-pink-500 bg-fixed">
                <div className="w-full max-w-7xl flex flex-row justify-start">
                    <h1 className="font-bold text-8xl sm:text-9xl text-white">
                        <FadeIn>Publication</FadeIn>
                    </h1>
                </div>
            </div>



        </main>
    );
}
