import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "team",
    description: "Generated by create next app",
    keywords: ["key1","key2"],
};



export default function Home() {
    return (
        <h1>team</h1>
    );
}
