import type { Metadata } from "next";
export const metadata: Metadata = {
    title: "home",
    description: "Generated by create next app",
    keywords: ["key1","key2"],
};



import { Button } from "@/components/ui/button"



export default function Home() {
    return (
        <div>
            <Button>Click me</Button>
            <h1>test</h1>
        </div>
    );
}
